#pragma once

#include <orbis/Pad.h>
#include <orbis/_types/pad.h>

#include "../include/types.h"

#define PAD_BUTTON_MODIFIER ORBIS_PAD_BUTTON_L1
#define PAD_BUTTON_TOGGLE_INPUTS (PAD_BUTTON_MODIFIER | ORBIS_PAD_BUTTON_OPTIONS)
#define PAD_BUTTON_INJECT (PAD_BUTTON_MODIFIER | ORBIS_PAD_BUTTON_R3)
#define PAD_BUTTON_NEXT_GSC (PAD_BUTTON_MODIFIER | ORBIS_PAD_BUTTON_RIGHT)
#define PAD_BUTTON_PREV_GSC (PAD_BUTTON_MODIFIER | ORBIS_PAD_BUTTON_LEFT)
